#' This function will make a request to the Google Management API with
#' the query prepared by the QueryBuilder() for retriving the GA Account
#' data.
#' @keywords internal 
#' @param query.uri The data feed query string generated by the Query builder Class.              
#' @return GA.Data The response as account data feed in the JSON format.
GetAcctDataFeedJSON <- function(query.uri) {
  
  GA.Data <- GET(query.uri)
  return(GA.Data)
}