#' @title
#' Retrieves the list of Profiles for the Google Analytics Account
#' 
#' This function retrieves all the available profiles from the 
#' Google analytics account which has been authenticated by the user
#' Before retrieving the list of profiles, this function checks the token 
#' for expiry  
#'  
#' @export 
#' 
#' @param token Token Object generated by \code{Auth()}
#' 
#' @return profiles R dataframe with profile id and profile name.

GetProfiles <- function(token) {
  
  ValidateToken(token)
  
  query.uri <- paste0('https://www.googleapis.com/analytics/v3/',
                      'management/accounts/~all/webproperties/~all/',
                      'profiles?access_token=',
                      token$credentials$access_token
  )
  if (!is.character(query.uri)) {
    stop("The query.uri parameter must be a character string")
  }
  
  # This api.reponse should be in json format
  api.response.json <- GetAcctDataFeedJSON(query.uri)
  profiles.param <- GetProfilesFromJSON(api.response.json)
  return(profiles.param$profiles)
}